export const langArr = {
  en: {
    link_project: "About the project",
    link_about_btn: "About project",
    stat_res: "of residential space",
    stat_com: "commercial spaces",
    stat_build: "residential-commercial buildings",
    stat_apr: "apartments",
    link_feat: "Features",
    p_dream: "LET YOUR LUXURY OASIS BE OUR RESPONSIBILITY",
    p_revolut: "THE COMPLEX IS REVOLUTIONIZING CONSTRUCTION...",
    h2_feat: "Complex Features",
    p_guest: "The Evolution Residence complex represents a new era...",
    t_personal: "By clicking the button, you agree to terms of processing",
    t_personal_data: "personal data",
    t_improve: `We’re currently improving our website.`,
    t_restore: `Full functionality will be restored soon.`,
    t_meantime: `In the meantime, please fill out the form below, and we’ll get
                back to you shortly.`,
    t_name: `Name`,
    t_phone: `Phone`,
    t_depart: `Sales department`,
    t_email: `E-mail`,
  },
  srb: {
    t_email: `E-mail`,
    t_phone: `Telefon`,
    t_depart: `Direktne prodaje`,
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "O projektu",
    link_about_btn: "O projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
  },
  ru:{
    t_email: `E-mail`,
    t_phone: `Telefon`,
    t_depart: `Direktne prodaje`,
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "O projektu",
    link_about_btn: "O projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
  },
};
