export const langArr = {
  en: {
    link_project: "About the project",
    link_about_btn: "About Project",
    about_title: "About",
    link_feat: "Features",
    link_infra: "Infrastructure",
    link_adv: "Advantages",
    link_equip: "Equipment",
    link_cont: "Contact",
    stat_res: "of residential space",
    stat_com: "commercial spaces",
    stat_build: "residential-commercial buildings",
    stat_apr: "apartments",
    p_dream: "LET YOUR LUXURY OASIS BE OUR RESPONSIBILITY",
    p_revolut: "THE COMPLEX IS REVOLUTIONIZING CONSTRUCTION...",
    h2_feat: "Complex Features",
    p_guest: "The Evolution Residence complex represents a new era...",
    t_personal: "By clicking the button, you agree to terms of processing",
    t_personal_data: "personal data",
    t_improve: `We’re currently improving our website.`,
    t_restore: `Full functionality will be restored soon.`,
    t_meantime: `In the meantime, please fill out the form below, and we’ll get
                back to you shortly.`,
    t_name: `Name`,
    t_phone: `Phone`,
    t_depart: `Sales department`,
    t_email: `E-mail`,
    t_req: `Leave a request`,
    t_apart: `Select an apartment`,
    t_welcome: `Welcome`,
    t_title: "Sopen park",
    t_subtitle: "A modern space for living and business in the heart of Niš",
    t_abouttitle: "Creating a space inspired by classics",
    t_about_text_1: `After the distinctive Beethoven's Park, which provided a home for families and individuals in a complex of 75 apartments, we continue to build in the same spirit — combining opulence, elegance, comfort and luxury.`,
    t_about_text_2: `Just as the world's greatest composers Beethoven and Chopin created music that inspires, our new commercial and residential complex, Chopin Park, exudes that artistic vision.`,
    t_locat: `Location`,
    t_complex_area: `Complex area`,
    t_num_apart: `Number of apartments`,
    t_park_space: `Parking spaces`,
    t_struct: `Structure`,
    t_abt_addr: `Niš, Serbia`,
    t_infra_title: `Everything here is designed for a modern lifestyle`,
    t_infra_blck_text: `Sopen Park invites you to be part of this new chapter in Niš.
                Join a community that values speed, quality, and comfort. Your
                new home, your story, Sopen Park`,
    sl_text_frst: `To take a leisurely stroll through the green alleys, breathe in the fresh air, 
      and enjoy the peaceful atmosphere`,
    sl_text_scnd: `Provide emergency care, specialized treatment, and academic medical programs`,
    sl_text_trhd: `Can enjoy dramatic performances, concerts, and festivals`,
    sl_text_frth: `You can indulge in a shopping experience`,
    sl_text_fift: `To step inside the monumental dome, feel the timeless serenity of sacred space, and admire the brilliance of Byzantine-inspired mosaics.`,
    sl_walk: `minutes walk`,
    sl_card: `minutes car`,
    sl_ili: `or`,
    sl_meters: `meters`,
    sl_km: `kilometer`,
    t_locatns: `Locations`,
    t_loc_txt_frst: `Chair Park`,
    t_loc_txt_secnd: `Clinical Center`,
    t_loc_txt_frtd: `Shoping Center`,
    t_loc_txt_frth: `St. Sava's Park`,
    t_loc_txt_fft: `King Milan sq.`,
    t_loc_txt_six: `King Alexander sq.`,
    t_loc_txt_seventh: `Fortress`,
    t_loc_txt_neinght: `Faculty of sports`,
    t_parallax_title: `A comfortable lifestyle within walking distance`,
  },
  srb: {
    t_parallax_title: `Uživajte u svakodnevnici — sve što vam je potrebno nalazi se na pešačkoj udaljenosti.`,
    t_locatns: `Lokacije`,
    sl_ili: `ili`,
    sl_meters: `metara`,
    sl_km: `km`,
    sl_walk: `minuta hoda`,
    sl_card: `minuta vožnje`,
    sl_text_frst: `Prošetajte kroz park, udahnite svež vazduh i uživajte u miru prirode`,
    sl_text_scnd: `Najbliži klinički centar, hitna pomoć i specijalizovane usluge`,
    sl_text_trhd: `Kulturni sadržaji – pozorište, koncerti, festivali`,
    sl_text_frth: `Tržni centri za potpunu šoping avanturu`,
    sl_text_fift: `Bogata istorija i impozantna arhitektura.`,
    t_infra_blck_text: `Šopen park vas poziva da postanete deo novog poglavlja u Nišu. Pridružite se zajednici koja ceni brzinu, kvalitet i udobnost. Vaš novi dom, vaša priča – Šopen park.`,
    t_infra_title: `Sve je osmišljeno za savremen način života`,
    t_abt_addr: `Niš, Srbija`,
    t_struct: `Spratnost`,
    t_num_apart: `Broj stanova`,
    t_park_space: `Broj parking mesta`,
    t_complex_area: `Površina kompleksa`,
    t_locat: `Lokacija`,
    t_about_text_1: `Nakon uspeha našeg projekta Beethoven's Park, koji 
    je postao dom za brojne porodice, nastavljamo da gradimo u istom duhu. 
    Kombinujemo raskoš, eleganciju i udobnost kako bismo stvorili mesto koje odiše stilom i toplinom.`,
    t_about_text_2: `Baš kao što su Betoven i Šopen svojim delima obeležili istoriju muzike, Šopen Park donosi umetničku viziju stanovanja — spoj funkcionalnosti i estetike u jedinstvenom ambijentu.`,
    t_abouttitle: "Inspirisani klasicima, stvaramo novi životni prostor",
    t_title: "ŠOPEN PARK",
    t_welcome: `Dobrodošli`,
    t_apart: `Izaberi stan`,
    t_req: `Pošalji zahtev`,
    t_email: `E-mail`,
    t_phone: `Telefon`,
    link_infra: "Infrastruktura",
    link_adv: "Prednosti",
    link_equip: "Opremljenost",
    link_cont: "Kontakt",
    t_depart: `Direktne prodaje`,
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "O projektu",
    link_about_btn: "O projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
    t_subtitle: "Moderan prostor za stanovanje i poslovanje u srcu Niša",
    about_title: `O projektu`,
    t_about_content_block: `Šopen Park nudi sofisticiran stil života — elegantni stanovi, moderno dizajnirani poslovni prostori i apartmani za poslovne ljude čine skladnu celinu za život u balansu.`,
    t_loc_txt_frst: `Čair park`,
    t_loc_txt_secnd: `Klinički centar`,
    t_loc_txt_frtd: `Tržni centar`,
    t_loc_txt_frth: `Park Svetog Save`,
    t_loc_txt_fft: `Trg kralja Milana`,
    t_loc_txt_six: `Trg kralja Aleksandra`,
    t_loc_txt_seventh: `Tvrđava`,
    t_loc_txt_neinght: `Fakultet sporta`,
  },
  ru: {
    t_parallax_title: `Uživajte u svakodnevnici — sve što vam je potrebno nalazi se na pešačkoj udaljenosti.`,
    t_loc_txt_frst: `Čair park`,
    t_loc_txt_secnd: `Klinički centar`,
    t_loc_txt_frtd: `Tržni centar`,
    t_loc_txt_frth: `Park Svetog Save`,
    t_loc_txt_fft: `Trg kralja Milana`,
    t_loc_txt_six: `Trg kralja Aleksandra`,
    t_loc_txt_seventh: `Tvrđava`,
    t_loc_txt_neinght: `Fakultet sporta`,
    t_locatns: `Lokacije`,
    sl_walk: `minuta hoda`,
    sl_card: `minuta vožnje`,
    sl_text_frst: `To take a leisurely stroll through the green alleys, breathe in the fresh air, 
      and enjoy the peaceful atmosphere`,
    sl_text_scnd: `Provide emergency care, specialized treatment, and academic medical programs`,
    sl_text_trhd: `Can enjoy dramatic performances, concerts, and festivals`,
    sl_text_frth: `You can indulge in a shopping experience`,
    sl_text_fift: `To step inside the monumental dome, feel the timeless serenity of sacred space, and admire the brilliance of Byzantine-inspired mosaics.`,
    t_infra_blck_text: ` Sopen Park invites you to be part of this new chapter in Niš.
                Join a community that values speed, quality, and comfort. Your
                new home, your story, Sopen Park`,
    t_infra_title: `Sve je osmišljeno za savremen način života`,
    t_abt_addr: `Niš, Serbia`,
    t_num_apart: `Broj stanova`,
    t_park_space: `Broj parking mesta`,
    t_struct: `Structure`,
    t_complex_area: `Površina kompleksa`,
    about_title: `O projektu`,
    t_about_content_block: `Šopen Park nudi sofisticiran stil života — elegantni stanovi, moderno dizajnirani poslovni prostori i apartmani za poslovne ljude čine skladnu celinu za život u balansu.`,
    t_about_text_2: `Baš kao što su Betoven i Šopen svojim delima obeležili istoriju muzike, Šopen Park donosi umetničku viziju stanovanja — spoj funkcionalnosti i estetike u jedinstvenom ambijentu.`,
    t_about_text_1: `Nakon uspeha našeg projekta Beethoven's Park, koji 
    je postao dom za brojne porodice, nastavljamo da gradimo u istom duhu. 
    Kombinujemo raskoš, eleganciju i udobnost kako bismo stvorili mesto koje odiše stilom i toplinom.`,
    t_abouttitle: "Creating a space inspired by classics",
    t_subtitle: "Moderan prostor za stanovanje i poslovanje u srcu Niša",
    t_title: "ŠOPEN PARK",
    t_req: `Leave a request`,
    t_welcome: `Dobrodošli`,
    t_apart: `Izaberi stan`,
    t_email: `E-mail`,
    t_phone: `Telefon`,
    t_depart: `Direktne prodaje`,
    link_infra: "Infrastructure",
    link_adv: "Prednosti",
    link_equip: "Opremljenost",
    link_cont: "Kontakt",
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "O projektu",
    link_about_btn: "O Projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
  },
};
