export const langArr = {
  en: {
    link_project: "Description",
    link_about_btn: "About Project",
    about_title: "About",
    link_feat: "Features",
    link_infra: "Infrastructure",
    link_adv: "Advantages",
    link_equip: "Equipment",
    link_cont: "Contact",
    stat_res: "of residential space",
    stat_com: "commercial spaces",
    stat_build: "residential-commercial buildings",
    stat_apr: "apartments",
    p_dream: "LET YOUR LUXURY OASIS BE OUR RESPONSIBILITY",
    p_revolut: "THE COMPLEX IS REVOLUTIONIZING CONSTRUCTION...",
    h2_feat: "Complex Features",
    p_guest: "The Evolution Residence complex represents a new era...",
    t_personal: "By clicking the button, you agree to terms of processing",
    t_personal_data: "personal data",
    t_improve: `We’re currently improving our website.`,
    t_restore: `Full functionality will be restored soon.`,
    t_meantime: `In the meantime, please fill out the form below, and we’ll get
                back to you shortly.`,
    t_name: `Name`,
    t_phone: `Phone`,
    t_depart: `Sales department`,
    t_depart_foot: `Sales department`,
    t_email: `Email`,
    t_req: `Leave a request`,
    t_apart: `Select an apartment`,
    t_welcome: `Welcome to`,
    t_title: "Sopen park",
    t_subtitle: "A modern space for living and business in the heart of Niš",
    t_abouttitle: "Creating a space inspired by classics",
    t_about_text_1: `After the distinctive Beethoven's Park, which provided a home for families and individuals in a complex of 75 apartments, we continue to build in the same spirit — combining opulence, elegance, comfort and luxury.`,
    t_about_text_2: `Just as the world's greatest composers Beethoven and Chopin created music that inspires, our new commercial and residential complex, Chopin Park, exudes that artistic vision.`,
    t_locat: `Location`,
    t_complex_area: `Complex area`,
    t_num_apart: `Number of apartments`,
    t_park_space: `Parking spaces`,
    t_struct: `Structure`,
    t_abt_addr: `Niš, Serbia`,
    t_infra_title: `Everything here is designed for a modern lifestyle`,
    t_infra_blck_text: `Sopen Park invites you to be part of this new chapter in Niš.
                Join a community that values speed, quality, and comfort. Your
                new home, your story, Sopen Park`,
    sl_text_frst: `Your new home is surrounded 
by natural and cultural landmarks – from Čair 
park and Park Svetog Save to central city 
spots such as Trg kralja Milana, Trg kralja 
Aleksandra, and the monumental Niška 
tvrđava`,
    sl_text_scnd: `Provide emergency care, specialized treatment, and academic medical programs`,
    sl_text_trhd: `Experience the cultural spirit of Niš through the National Theatre, 
concerts and festivals at Trg kralja Milana, and events in the impressive Niška tvrđava. 
Whether you enjoy theatre, music, or open-air manifestations, everything is just minutes 
away from your new home`,
    sl_text_frth: `You can indulge in a shopping experience`,
    sl_text_fift: `The suggestion is to 
replace it with a photograph of cultural and historical landmarks or architectural symbols that are universally recognizable`,
    sl_walk: `minutes walk`,
    sl_card: `minutes car`,
    sl_ili: `or`,
    sl_meters: `meters`,
    sl_km: `kilometer`,
    t_locatns: `Locations`,
    t_loc_txt_frst: `Chair Park`,
    t_loc_txt_secnd: `Clinical Center`,
    t_loc_txt_frtd: `Shoping Center`,
    t_loc_txt_frth: `St. Sava's Park`,
    t_loc_txt_fft: `King Milan sq.`,
    t_loc_txt_six: `King Alexander sq.`,
    t_loc_txt_seventh: `Fortress`,
    t_loc_txt_neinght: `Faculty of sports`,
    t_parallax_title: `A comfortable lifestyle within walking distance`,
    t_link_fin: `Finance`,
    t_space_str: `Space Structure`,
    t_anot: `All rights reserved © 2025 Sopen Park`,
    t_hor_par_1: `Residents don’t have to travel far to enjoy themselves — entertainment is delivered right to their doorstep.`,
    t_hor_par_2: `Wellness center`,
    t_hor_par_3: `Supermarket`,
    t_hor_par_4: `Pharmacy`,
    t_hor_par_5: `Café`,
    t_hor_par_6: `Business apartments`,
    t_hor_par_7: `Other commercial spaces`,
    t_equip_title: `Quality in every detail: comfort and security`,
    t_equip_name_1: `Thermal insulation`,
    t_equip_name_2: `Facade carpentry`,
    t_equip_name_3: `Climate control`,
    t_equip_name_4: `Access control`,
    t_equip_name_5: `Entrance doors`,
    t_equip_name_6: `Interior doors`,
    t_equip_name_7: `Flooring`,
    t_equip_name_8: `Ceramics`,
    t_equip_name_9: `Plumbing`,
    t_equip_discr_1: `Facade walls made of high-quality economical blocks, thermal insulation with 12 cm polystyrene.`,
    t_equip_discr_2: `High-quality multi-chamber PVC`,
    t_equip_discr_3: `Split-system air conditioning in the living room.`,
    t_equip_discr_4: `Video intercom at the entrance to each section.`,
    t_equip_discr_5: `Protective entrance doors with high fire resistance.`,
    t_equip_discr_6: `MDF doors covered with white CPL film.`,
    t_equip_discr_7: `Multi-layer parquet from a renowned manufacturer.`,
    t_equip_discr_8: `First-class ceramic tiles.`,
    t_equip_discr_9: `Plumbing and sanitary equipment from collections of leading global manufacturers.`,
    t_fin_title: `Savings and comfort: invest in your future`,
    t_main_cond: `Main conditions`,
    t_fin_name_1: `Housing credit API Bank`,
    t_fin_name_2: `Housing credit Banca Intesa`,
    t_fin_name_3: `Housing credit UniCredit Bank`,
    t_fin_txt_1_1: `No Serbian residency required. You can purchase an apartment in Sava Residence through API Bank, even if you are not a resident of Serbia.`,
    t_fin_txt_1_2: `Flexible income assessment. To determine your creditworthiness, API Bank accepts all types of income, not just salaries.
Flexible income assessment. To determine your creditworthiness, API Bank accepts all types of income, not just salaries.`,
    t_fin_txt_1_3: `Path to residency. The property you purchase can be a basis for obtaining a residence permit in Serbia.`,
    t_fin_txt_1_4: `Loan consultation. Leave your details, and an API Bank housing loan advisor will contact you.`,
    t_fin_txt_2_1: `Special Loan Conditions. Banca Intesa offers favorable terms for housing loans to purchase property in our complex, including a fixed interest rate of 5.03%.`,
    t_fin_txt_2_2: `Fast and Easy Processing. Financing real estate in Sava Residence is a simple and efficient procedure, taking only 7 days from the date of application submission.`,
    t_fin_txt_2_3: `Path to residency. The property you purchase can be a basis for obtaining a residence permit in Serbia.`,
    t_fin_txt_2_4: `Loan Consultation. If you need additional details, leave your contact information, and a Banca Intesa housing loan advisor will get in touch with you.`,
    t_fin_txt_3_1: `Attractive Rates. Fixed or variable interest rates from ~3.19% (EUR loans`,
    t_fin_txt_3_2: `Fast Processing. Simple procedure with quick approval times.`,
    t_fin_txt_3_3: `Path to residency. Property purchase may help obtain a Serbian residence permit.`,
    t_fin_txt_3_4: `Loan Consultation. Leave your details for a UniCredit Bank advisor to contact you.`,
    t_struct_title: `Thoughtful layout for modern living`,
    t_struct_name_1: `Lamela A`,
    t_struct_name_2: `Lamela B and C`,
    t_struct_name_3: `Parking`,
    t_struct_txt_1_1: `A majestic 15-story tower featuring 182 residential units.`,
    t_struct_txt_1_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_2_1: `Harmonious residential spaces with a height of 10 stories, each containing 72 apartments.`,
    t_struct_txt_2_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_3_1: `Parking spaces are located on three underground levels.`,
    t_struct_txt_3_2: `Elevators provide direct access between the parking area and residential floors, ensuring convenience and maximum comfort for residents.`,
    t_apart_view_title: `Step Towards Your New Home`,
    t_apart_view_filter: `filter by features`,
    t_apart_view_selet_text: `visual selectional of apartments`,
    t_get_dir_btn: `Get directions`,
    t_cont: `Contact`,
    t_form_title: `Request a call`,
    t_form_err_txt: `Wrong email or name`,
    t_about_content_block: `Chopin Park offers a refined living experience, blending luxury with functionality. Thoughtfully designed, it provides elegant homes, commercial spaces, wellness facilities, and business apartments for a balanced lifestyle.`,
    t_apart_title: `Apartments`,
    t_apart_txt: `options`,
    t_lam_txt: `Section`,
    t_flor_txt: `Floor`,
    t_area_txt: `Area`,
    t_reset_txt: `Reset`,
    t_show_more_txt: `Show more`,
    t_grid_view_txt: `Grid view`,
    t_flor_plan_txt: `Floor plan`,
    t_sort_area_txt: `Sorted by increasing area`,
    t_sort_flor_txt: `Sorted by increasing floor`,
    t_sort_sect_txt: `Sorted by increasing section`,
    t_filter_param_txt: `Filter by features`,
    t_bread_main_txt: `Main`,
    t_pr_upon_txt: `price upon request`,
    t_build_wing_txt: `Building wing`,
    t_back_txt: `Back`,
    t_hallway: `Hallway`,
    t_living: `Livingroom`,
    t_bath: `Bathroom`,
    t_bedrom: `Bedroom`,
    t_terace: `Terrace`,
    t_rooms: `rooms`,
    t_plan_view_txt: `plan view`,
    t_3d_view_txt: `3d  view`,
    t_par_descrt: `The finished objects may differ from the 3D visualizations provided. All materials provided are indicative only and are subject to change`,
  },
  srb: {
    t_rooms: `sobe`,
    t_par_descrt: `Završeni objekti mogu se razlikovati od prikazanih 3D vizualizacija. Svi dostavljeni materijali su samo informativnog karaktera i podložni su izmenama`,
    t_plan_view_txt: `Plan prostora`,
    t_3d_view_txt: `3d prostora`,
    t_back_txt: `Nazad`,
    t_build_wing_txt: `Krilo zgrade`,
    t_pr_upon_txt: `Cena na upit`,
    t_bread_main_txt: `Glavni`,
    t_filter_param_txt: `Filtriraj po karakteristikama`,
    t_sort_area_txt: `Sortirano po povećanju površine`,
    t_sort_flor_txt: `Sortirano po povećanju sprata`,
    t_sort_sect_txt: `Sortirano po povećanju lamele`,
    t_flor_plan_txt: `Plan sprata`,
    t_show_more_txt: `Prikaži više`,
    t_flor_txt: `Sprat`,
    t_apart_txt: `ponuda`,
    t_apart_title: `Stanovi`,
    t_form_err_txt: `Pogrešan e-mail ili ime`,
    t_depart_foot: `Prodajno odeljenje`,
    t_cont: `Kontakt`,
    t_get_dir_btn: `Prikaži putanju`,
    t_apart_view_selet_text: `vizuelni izbor stanova`,
    t_apart_view_filter: `Filter po karakteristikama`,
    t_apart_view_title: `Korak bliže ka vašem novom domu`,
    t_struct_name_1: `Lamela A`,
    t_struct_name_2: `Lamele B i C`,
    t_struct_name_3: `Parking`,
    t_struct_txt_1_1: `Impozantna kula od 15 spratova sa 182 stana — spoj inženjerske preciznosti i elegantnog dizajna.`,
    t_struct_txt_1_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_2_1: ` Zgrade od po 10 spratova sa 72 stana – harmonično uklopljene u ambijent.`,
    t_struct_txt_2_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_3_1: `Parking spaces are located on three underground levels.`,
    t_struct_txt_3_2: `Tri nivoa sa direktnim pristupom liftovima – maksimalna udobnost i sigurnost.`,
    t_struct_title: `Savremena arhitektura za funkcionalan životni prostor`,
    t_fin_name_1: `Stambeni kredit API Banka`,
    t_fin_name_2: `Stambeni kredit Banca Intesa`,
    t_fin_name_3: `Stambeni kredit UniCredit Bank`,
    t_fin_txt_1_1: `Nije potreban boravak u Srbiji`,
    t_fin_txt_1_2: `Fleksibilna procena prihoda`,
    t_fin_txt_1_3: `Nekretnina kao osnov za boravišnu dozvolu`,
    t_fin_txt_1_4: `Konsultacija sa bankarskim savetnikom`,
    t_fin_txt_2_1: `Fiksna kamatna stopa 5.03%`,
    t_fin_txt_2_2: `Brza obrada (7 dana)`,
    t_fin_txt_2_3: `Mogućnost boravišne dozvole`,
    t_fin_txt_2_4: `Besplatna konsultacija`,
    t_fin_txt_3_1: `Kamatna stopa od ~3.19%`,
    t_fin_txt_3_2: `Brza obrada`,
    t_fin_txt_3_3: `Mogućnost boravišne dozvole`,
    t_fin_txt_3_4: `Konsultacija sa savetnikom`,
    t_main_cond: `Glavni uslovi`,
    t_fin_title: `Ušteda i udobnost: investirajte u svoju budućnost`,
    t_equip_name_1: `Toplotna izolacija`,
    t_equip_name_2: `Fasadna stolarija`,
    t_equip_name_3: `Klimatizacija`,
    t_equip_name_4: `Kontrola pristupa`,
    t_equip_name_5: `Ulazna vrata`,
    t_equip_name_6: `Unutrašnja vrata`,
    t_equip_name_7: `Podne obloge`,
    t_equip_name_8: `Keramika`,
    t_equip_name_9: `Sanitarije`,
    t_equip_discr_1: `Fasadne zidove čine kvalitetni blokovi, izolacija kamenom vunom od 12 cm.`,
    t_equip_discr_2: `Višekomorni PVC visokog kvaliteta.`,
    t_equip_discr_3: `Split sistem u dnevnoj sobi.`,
    t_equip_discr_4: `Video-interfon na ulazu svake sekcije.`,
    t_equip_discr_5: `Sigurnosna, protivpožarna vrata.`,
    t_equip_discr_6: `MDF vrata sa CPL folijom u beloj boji.`,
    t_equip_discr_7: `Višeslojni parket renomiranog proizvođača.`,
    t_equip_discr_8: `Prvoklasne keramičke pločice.`,
    t_equip_discr_9: `Oprema vodećih svetskih brendova.`,
    t_equip_title: `Kvalitet u svakom detalju: udobnost i sigurnost`,
    t_hor_par_1: `Stanari ne moraju daleko da putuju da bi uživali – zabava im je na samom pragu.`,
    t_hor_par_2: `Velnes centar`,
    t_hor_par_3: `Supermarket`,
    t_hor_par_4: `Apoteka`,
    t_hor_par_5: `Kafić`,
    t_hor_par_6: `Poslovni apartmani`,
    t_hor_par_7: `Ostali komercijalni prostori`,
    t_anot: `Sva prava zadržana © 2025 Šopen Park`,
    t_space_str: `Struktura prostora`,
    t_link_fin: `Finansije`,
    t_parallax_title: `Uživajte u svakodnevnici — sve što vam je potrebno nalazi se na pešačkoj udaljenosti`,
    t_locatns: `Lokacije`,
    sl_ili: `ili`,
    sl_meters: `metara`,
    sl_km: `km`,
    sl_walk: `minuta hoda`,
    sl_card: `minuta vožnje`,
    sl_text_frst: `Vaš novi dom okružen je prirodnim i kulturnim znamenitostima – od Čair parka i Parka Svetog Save do centralnih gradskih tačaka kao što su Trg kralja Milana, Trg kralja Aleksandra i monumentalna Niška tvrđava`,
    sl_text_scnd: `Najbliži klinički centar, hitna pomoć i specijalizovane usluge`,
    sl_text_trhd: `Doživite kulturni duh Niša kroz Narodno pozorište, koncerte i festivale na Trgu kralja Milana, kao i događaje u impresivnoj Niškoj tvrđavi. Bilo da volite pozorište, muziku ili manifestacije na otvorenom, sve vam je na samo nekoliko minuta od novog doma`,
    sl_text_frth: `Tržni centri za potpunu šoping avanturu`,
    sl_text_fift: `Predlog je da se zameni fotografijom kulturnih i istorijskih znamenitosti ili arhitektonskih simbola koji su univerzalno prepoznatljivi`,
    t_infra_blck_text: `Šopen park vas poziva da postanete deo novog poglavlja u Nišu. Pridružite se zajednici koja ceni brzinu, kvalitet i udobnost. Vaš novi dom, vaša priča – Šopen park.`,
    t_infra_title: `Sve je osmišljeno za savremen način života`,
    t_abt_addr: `Niš, Srbija`,
    t_struct: `Spratnost`,
    t_num_apart: `Broj stanova`,
    t_park_space: `Broj parking mesta`,
    t_complex_area: `Površina kompleksa`,
    t_locat: `Lokacija`,
    t_about_text_1: `Nakon uspeha našeg projekta Beethoven's Park, koji 
    je postao dom za brojne porodice, nastavljamo da gradimo u istom duhu. 
    Kombinujemo raskoš, eleganciju i udobnost kako bismo stvorili mesto koje odiše stilom i toplinom.`,
    t_about_text_2: `Baš kao što su Betoven i Šopen svojim delima obeležili istoriju muzike, Šopen Park donosi umetničku viziju stanovanja — spoj funkcionalnosti i estetike u jedinstvenom ambijentu.`,
    t_abouttitle: "Inspirisani klasicima, stvaramo novi životni prostor",
    t_title: "ŠOPEN PARK",
    t_welcome: `Dobrodošli`,
    t_apart: `Izaberi stan`,
    t_req: `Pošalji zahtev`,
    t_email: `Email`,
    t_phone: `Telefon`,
    link_infra: "Infrastruktura",
    link_adv: "Prednosti",
    link_equip: "Opremljenost",
    link_cont: "Kontakt",
    t_depart: `Direktne prodaje`,
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "Opis",
    link_about_btn: "O projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
    t_subtitle: "Moderan prostor za stanovanje i poslovanje u srcu Niša",
    about_title: `O projektu`,
    t_about_content_block: `Šopen Park nudi sofisticiran stil života — elegantni stanovi, moderno dizajnirani poslovni prostori i apartmani za poslovne ljude čine skladnu celinu za život u balansu.`,
    t_loc_txt_frst: `Čair park`,
    t_loc_txt_secnd: `Klinički centar`,
    t_loc_txt_frtd: `Tržni centar`,
    t_loc_txt_frth: `Park Svetog Save`,
    t_loc_txt_fft: `Trg kralja Milana`,
    t_loc_txt_six: `Trg kralja Aleksandra`,
    t_loc_txt_seventh: `Tvrđava`,
    t_loc_txt_neinght: `Fakultet sporta`,
    t_form_title: `Zatražite poziv`,
    t_lam_txt: `Lamela`,
    t_area_txt: `Površina`,
    t_reset_txt: `Poništi`,
    t_grid_view_txt: `Mrežni prikaz`,
    t_hallway: `Hodnik`,
    t_living: `Dnevna soba`,
    t_bath: `Kupatilo`,
    t_bedrom: `Spavaća soba`,
    t_terace: `Terasa`,
  },
  ru: {
    t_rooms: `rooms`,
    t_par_descrt: `The finished objects may differ from the 3D visualizations provided. All materials provided are indicative only and are subject to change`,
    t_plan_view_txt: `plan view`,
    t_3d_view_txt: `3d  view`,
    t_hallway: `Hallway`,
    t_living: `Livingroom`,
    t_bath: `Bathroom`,
    t_bedrom: `Bedroom`,
    t_terace: `Terrace`,
    t_back_txt: `Back`,
    t_build_wing_txt: `Building wing`,
    t_pr_upon_txt: `price upon request`,
    t_filter_param_txt: `Filter by features`,
    t_bread_main_txt: `Main`,
    t_sort_area_txt: `Sorted by increasing area`,
    t_sort_flor_txt: `Sorted by increasing floor`,
    t_sort_sect_txt: `Sorted by increasing section`,
    t_flor_plan_txt: `Floor plan`,
    t_grid_view_txt: `Grid view`,
    t_show_more_txt: `Show more`,
    t_reset_txt: `Reset`,
    t_area_txt: `Area`,
    t_flor_txt: `Floor`,
    t_lam_txt: `Section`,
    t_apart_txt: `options`,
    t_apart_title: `Apartments`,
    t_locat: `Location`,
    sl_ili: `or`,
    sl_meters: `meters`,
    sl_km: `kilometer`,
    t_form_err_txt: `Wrong email or name`,
    t_form_title: `Request a call`,
    t_depart_foot: `Sales department`,
    t_cont: `Contact`,
    t_get_dir_btn: `Get directions`,
    t_apart_view_selet_text: `visual selectional of apartments`,
    t_apart_view_filter: `filter by features`,
    t_apart_view_title: `Step Towards Your New Home`,
    t_struct_name_1: `Lamela A`,
    t_struct_name_2: `Lamela B and C`,
    t_struct_name_3: `Parking`,
    t_struct_txt_1_1: `A majestic 15-story tower featuring 182 residential units.`,
    t_struct_txt_1_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_2_1: `Harmonious residential spaces with a height of 10 stories, each containing 72 apartments.`,
    t_struct_txt_2_2: `Thanks to modern engineering solutions and elegant design, it shapes the distinctive architectural character of the complex.`,
    t_struct_txt_3_1: `Parking spaces are located on three underground levels.`,
    t_struct_txt_3_2: `Elevators provide direct access between the parking area and residential floors, ensuring convenience and maximum comfort for residents.`,
    t_struct_title: `Thoughtful layout for modern living`,
    t_fin_name_1: `Housing credit API Bank`,
    t_fin_name_2: `Housing credit Banca Intesa`,
    t_fin_name_3: `Housing credit UniCredit Bank`,
    t_fin_txt_1_1: `No Serbian residency required. You can purchase an apartment in Sava Residence through API Bank, even if you are not a resident of Serbia.`,
    t_fin_txt_1_2: `Flexible income assessment. To determine your creditworthiness, API Bank accepts all types of income, not just salaries.
Flexible income assessment. To determine your creditworthiness, API Bank accepts all types of income, not just salaries.`,
    t_fin_txt_1_3: `Path to residency. The property you purchase can be a basis for obtaining a residence permit in Serbia.`,
    t_fin_txt_1_4: `Loan consultation. Leave your details, and an API Bank housing loan advisor will contact you.`,
    t_fin_txt_2_1: `Special Loan Conditions. Banca Intesa offers favorable terms for housing loans to purchase property in our complex, including a fixed interest rate of 5.03%.`,
    t_fin_txt_2_2: `Fast and Easy Processing. Financing real estate in Sava Residence is a simple and efficient procedure, taking only 7 days from the date of application submission.`,
    t_fin_txt_2_3: `Path to residency. The property you purchase can be a basis for obtaining a residence permit in Serbia.`,
    t_fin_txt_2_4: `Loan Consultation. If you need additional details, leave your contact information, and a Banca Intesa housing loan advisor will get in touch with you.`,
    t_fin_txt_3_1: `Attractive Rates. Fixed or variable interest rates from ~3.19% (EUR loans`,
    t_fin_txt_3_2: `Fast Processing. Simple procedure with quick approval times.`,
    t_fin_txt_3_3: `Path to residency. Property purchase may help obtain a Serbian residence permit.`,
    t_fin_txt_3_4: `Loan Consultation. Leave your details for a UniCredit Bank advisor to contact you.`,
    t_main_cond: `Main conditions`,
    t_fin_title: `Savings and comfort: invest in your future`,
    t_equip_name_1: `Thermal insulation`,
    t_equip_name_2: `Facade carpentry`,
    t_equip_name_3: `Climate control`,
    t_equip_name_4: `Access control`,
    t_equip_name_5: `Entrance doors`,
    t_equip_name_6: `Interior doors`,
    t_equip_name_7: `Flooring`,
    t_equip_name_8: `Ceramics`,
    t_equip_name_9: `Plumbing`,
    t_equip_discr_1: `The facade walls are made of high-quality blocks with 12 cm thick stone wool insulation.`,
    t_equip_discr_2: `High-quality multi-chamber PVC`,
    t_equip_discr_3: `Split-system air conditioning in the living room.`,
    t_equip_discr_4: `Video intercom at the entrance to each section.`,
    t_equip_discr_5: `Protective entrance doors with high fire resistance.`,
    t_equip_discr_6: `MDF doors covered with white CPL film.`,
    t_equip_discr_7: `Multi-layer parquet from a renowned manufacturer.`,
    t_equip_discr_8: `First-class ceramic tiles.`,
    t_equip_discr_9: `Plumbing and sanitary equipment from collections of leading global manufacturers.`,
    t_equip_title: `Quality in every detail: comfort and security`,
    t_hor_par_1: `Residents don’t have to travel far to enjoy themselves — entertainment is delivered right to their doorstep.`,
    t_hor_par_2: `Wellness center`,
    t_hor_par_3: `Supermarket`,
    t_hor_par_4: `Pharmacy`,
    t_hor_par_5: `Café`,
    t_hor_par_6: `Business apartments`,
    t_hor_par_7: `Other commercial spaces`,
    t_anot: `All rights reserved © 2025 Sopen Park`,
    t_space_str: `Space Structure`,
    t_link_fin: `Finance`,
    t_parallax_title: `A comfortable lifestyle within walking distance`,
    t_loc_txt_frst: `Čair park`,
    t_loc_txt_secnd: `Klinički centar`,
    t_loc_txt_frtd: `Tržni centar`,
    t_loc_txt_frth: `Park Svetog Save`,
    t_loc_txt_fft: `Trg kralja Milana`,
    t_loc_txt_six: `Trg kralja Aleksandra`,
    t_loc_txt_seventh: `Tvrđava`,
    t_loc_txt_neinght: `Fakultet sporta`,
    t_locatns: `Lokacije`,
    sl_walk: `minuta hoda`,
    sl_card: `minuta vožnje`,
    sl_text_frst: `Your new home is surrounded 
by natural and cultural landmarks – from Čair 
park and Park Svetog Save to central city 
spots such as Trg kralja Milana, Trg kralja 
Aleksandra, and the monumental Niška 
tvrđava`,
    sl_text_scnd: `Provide emergency care, specialized treatment, and academic medical programs`,
    sl_text_trhd: `Experience the cultural spirit of Niš through the National Theatre, 
concerts and festivals at Trg kralja Milana, and events in the impressive Niška tvrđava. 
Whether you enjoy theatre, music, or open-air manifestations, everything is just minutes 
away from your new home`,
    sl_text_frth: `You can indulge in a shopping experience`,
    sl_text_fift: `The suggestion is to 
replace it with a photograph of cultural and historical landmarks or architectural symbols that are universally recognizable`,
    t_infra_blck_text: ` Sopen Park invites you to be part of this new chapter in Niš.
                Join a community that values speed, quality, and comfort. Your
                new home, your story, Sopen Park`,
    t_infra_title: `Sve je osmišljeno za savremen način života`,
    t_abt_addr: `Niš, Serbia`,
    t_num_apart: `Broj stanova`,
    t_park_space: `Broj parking mesta`,
    t_struct: `Structure`,
    t_complex_area: `Površina kompleksa`,
    about_title: `O projektu`,
    t_about_content_block: `Šopen Park nudi sofisticiran stil života — elegantni stanovi, moderno dizajnirani poslovni prostori i apartmani za poslovne ljude čine skladnu celinu za život u balansu.`,
    t_about_text_2: `Baš kao što su Betoven i Šopen svojim delima obeležili istoriju muzike, Šopen Park donosi umetničku viziju stanovanja — spoj funkcionalnosti i estetike u jedinstvenom ambijentu.`,
    t_about_text_1: `Nakon uspeha našeg projekta Beethoven's Park, koji 
    je postao dom za brojne porodice, nastavljamo da gradimo u istom duhu. 
    Kombinujemo raskoš, eleganciju i udobnost kako bismo stvorili mesto koje odiše stilom i toplinom.`,
    t_abouttitle: "Creating a space inspired by classics",
    t_subtitle: "Moderan prostor za stanovanje i poslovanje u srcu Niša",
    t_title: "ŠOPEN PARK",
    t_req: `Leave a request`,
    t_welcome: `Dobrodošli`,
    t_apart: `Izaberi stan`,
    t_email: `Email`,
    t_phone: `Telefon`,
    t_depart: `Direktne prodaje`,
    link_infra: "Infrastructure",
    link_adv: "Prednosti",
    link_equip: "Opremljenost",
    link_cont: "Kontakt",
    t_name: `Ime`,
    t_meantime: `U međuvremenu, molimo vas da popunite formular ispod, i javićemo vam se uskoro.`,
    t_restore: `Puna funkcionalnost će uskoro biti ponovo dostupna.`,
    t_improve: `Trenutno radimo na unapređenju naše veb stranice.`,
    link_project: "Opis",
    link_about_btn: "O Projektu",
    stat_res: "stambenog prostora",
    stat_com: "poslovnih prostora",
    stat_build: "stambeno-poslovne zgrade",
    stat_apr: "stanova",
    link_feat: "Karakteristike",
    p_dream: "NEKA VAŠ LUKSUZNI OAZA BUDE NAŠA ODGOVORNOST",
    p_revolut: "KOMPLEKS REVOLUCIONIRA GRAĐEVINARSTVO...",
    h2_feat: "Karakteristike kompleksa",
    p_guest: "Kompleks Evolution Residence predstavlja novu eru...",
    t_personal: "Klikom na dugme, pristajete na uslove obrade ",
    t_personal_data: "ličnih podataka",
  },
};
